### PR TITLE
Update for jsxstyle 2.0.0

### PR DESCRIPTION
**Pull request by sgwilym**
Updates this package for the API of jest-jsxstyle@2.0.0, which now exports a cache object with its own API for resetting and adding injection rules.

Also makes it so that the serialised CSS rules are pretty printed, which IMO makes them easier to read and look at diffs for.

### CODE REVIEW

**Comment by sgwilym** [comment]
Also, would you be so kind as to cut this in with a new release and publish this update to NPM?

**Comment by jaredpalmer** [comment]
yup

**Comment by sgwilym** [comment]
🙌

**Comment by sgwilym** [comment]
Hey @jaredpalmer, looks like the lib didn't rebuild before you published it, as grabbing this on NPM shows this having the new version number but the old implementation.

**Comment by jaredpalmer** [comment]
woops maybe forgot to pull

**Comment by jaredpalmer** [comment]
https://unpkg.com/jest-jsxstyle@2.0.1/dist/serializer.js looks correct?

**Comment by sgwilym** [comment]
Perfect, thanks!

**Pull request merged**
